### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by SonicCraft** [yolopix-dotfledge/pixel-gun-3d-assets#1]
Do you know where i can find the extra 4,127 missing files?  Thanks!
![fireshot capture 3 - pixel-gun-3d-assets_extracted_texture2_ - https___github com_yolopix-dotfledg](https://user-images.githubusercontent.com/39831475/40842060-9d367f42-657a-11e8-87e7-906ad8677b19.png)

**Comment by yolopix-dotfledge** [comment]
The files are not missing, they are just truncated by GitHub. To see all files, you can clone this repository with this command:
``git clone --depth=1 https://github.com/yolopix-dotfledge/pixel-gun-3d-assets``
It might take some time if you don't have a good internet connection.

**Comment by TrashCraftPayer** [comment]
how do I access the commands ?

**Comment by yolopix-dotfledge** [comment]
> how do I access the commands ?
If you are on Windows, you must [download Git](https://git-scm.com/download/win) and type the command in the Git CMD program.
If you are on Linux, you must enter the terminal to type the command. If Git is not preinstalled you can type `sudo apt install git`.
